### ISSUE TITLE
roadmap: migration of mercurius-gateway

### ISSUE THREAD

**Issue by marco-ippolito** [mercurius-js/mercurius#929]
I'm creating a roadmap to keep track of the work on the migration of `mercurius-gateway` as npm dependency.

- [x]  create `mercurius-subscription-client` https://github.com/mercurius-js/mercurius-subscription-client/issues/2 @marco-ippolito 
- [x] release `mercurius-subscription-client` on npm https://www.npmjs.com/package/@mercuriusjs/subscription-client
- [x] change `subscription-client` on the gateway with the new package https://github.com/mercurius-js/mercurius-gateway/pull/49 @marco-ippolito 
- [x] remove `subscription-client` from `mercurius/lib` https://github.com/mercurius-js/mercurius/pull/938 @marco-ippolito supersedes: https://github.com/mercurius-js/mercurius/pull/920 @Mazuh 
- [x] release `mercurius-gateway` on npm @mcollina 
- [ ] remove `gateway` from `mercurius/lib` https://github.com/mercurius-js/mercurius/pull/942 @marco-ippolito

**Comment by Mazuh** [comment]
> remove subscription-client from mercurius/lib

I'm going to work on it.

**Comment by Mazuh** [comment]
I left a PR open: https://github.com/mercurius-js/mercurius/pull/930
but it's blocked until https://github.com/mercurius-js/mercurius/pull/916 gets merged.

**Comment by mcollina** [comment]
@marco-ippolito could you finish this up?

**Comment by marco-ippolito** [comment]
@mcollina should we remove the gateway and the subscription client from mercurius before or after releasing mercurius-gateway?

**Comment by marco-ippolito** [comment]
@mcollina any blockers on the release on mercurius-gateway we can help? should we take over @codeflyer pr on removing gateway from mercurius?  what are the next steps?

**Comment by mcollina** [comment]
I've released the new gateway. @marco-ippolito could you finish https://github.com/mercurius-js/mercurius/pull/916?
